/**
 * seed.local.ts — Local development seed (no Supabase required)
 *
 * Use this when running against a local Postgres instance (Docker).
 * Skips Supabase Auth user creation entirely — Prisma generates user IDs via cuid().
 * Requires DISABLE_AUTH=true in .env to bypass JWT verification.
 *
 * Usage: pnpm db:seed:local
 */

import { PrismaClient, FacilityType, Urgency, UserRole, BinStatus } from '@prisma/client';
import { PrismaPg } from '@prisma/adapter-pg';
import { randomBytes } from 'crypto';

function generateToken(): string {
    return randomBytes(32).toString('hex');
}

// ─── Seed Users ─────────────────────────────────────────────────────────────
// IDs are auto-generated by Prisma (cuid). No Supabase required.
// Passwords are listed here for reference only — not stored in the DB since
// there's no auth system in local mode. Log in via DISABLE_AUTH=true.

const SEED_USERS = [
    { email: 'admin@bintracker.com',   name: 'System Admin',  role: UserRole.ADMIN },
    { email: 'ops@bintracker.com',     name: 'Ops Manager',   role: UserRole.OPS_MANAGER },
    { email: 'driver1@bintracker.com', name: 'John Driver',   role: UserRole.DRIVER },
    { email: 'driver2@bintracker.com', name: 'Jane Driver',   role: UserRole.DRIVER },
    { email: 'worker1@bintracker.com', name: 'Bob Worker',    role: UserRole.WORKER },
] as const;

// ─── Main ────────────────────────────────────────────────────────────────────

async function main(): Promise<void> {
    const adapter = new PrismaPg({ connectionString: process.env['DATABASE_URL'] });
    const prisma = new PrismaClient({ adapter, log: [] });

    // ─── Safety guard (matches masumi-payment-service pattern) ────
    // Set SEED_ONLY_IF_EMPTY=true in .env to skip if data already exists.
    // Prevents accidental re-wipes when running seed a second time.
    if (process.env['SEED_ONLY_IF_EMPTY']?.toLowerCase() === 'true') {
        const existing = await prisma.user.findFirst();
        if (existing) {
            console.log('✅ Database already seeded — skipping (SEED_ONLY_IF_EMPTY=true)');
            await prisma.$disconnect();
            return;
        }
    }
    // ─── 1. Clean DB (FK constraint order matters) ────────────────
    console.log('🧹 Cleaning existing data...');
    await prisma.eventLog.deleteMany();
    await prisma.binCycle.deleteMany();
    await prisma.bin.deleteMany();
    await prisma.station.deleteMany();
    await prisma.binType.deleteMany();
    await prisma.userFacility.deleteMany();
    await prisma.user.deleteMany();
    await prisma.facility.deleteMany();

    // ─── 2. Create users (Prisma generates cuid IDs) ──────────────
    console.log('👤 Creating local users (no Supabase, cuid IDs)...');
    const dbUsers = await Promise.all(
        SEED_USERS.map(u =>
            prisma.user.create({
                data: { email: u.email, name: u.name, role: u.role },
                // No `id` → Prisma auto-generates a cuid()
            }),
        ),
    );
    const [, ops, driver1, driver2] = dbUsers;

    // ─── 3. Facilities ────────────────────────────────────────────
    console.log('🏭 Creating facilities...');
    const facilities = await Promise.all([
        prisma.facility.create({ data: { name: 'Chicago Processing',   type: FacilityType.PROCESSING, address: '123 Industrial Blvd, Chicago, IL 60601',       lat: 41.8781, lng: -87.6298 } }),
        prisma.facility.create({ data: { name: 'Detroit Processing',   type: FacilityType.PROCESSING, address: '456 Factory Ave, Detroit, MI 48201',             lat: 42.3314, lng: -83.0458 } }),
        prisma.facility.create({ data: { name: 'Milwaukee Processing', type: FacilityType.PROCESSING, address: '789 Plant Rd, Milwaukee, WI 53202',              lat: 43.0389, lng: -87.9065 } }),
        prisma.facility.create({ data: { name: 'Midwest Rendering',    type: FacilityType.RENDERING,  address: '321 Render Lane, Indianapolis, IN 46201',        lat: 39.7684, lng: -86.1581 } }),
        prisma.facility.create({ data: { name: 'Great Lakes Rendering',type: FacilityType.RENDERING,  address: '654 Process Way, Columbus, OH 43215',            lat: 39.9612, lng: -82.9988 } }),
    ]);
    const [chicago, detroit, milwaukee] = facilities;

    // ─── 4. Assign users to facilities ───────────────────────────
    //  ADMIN   → no assignment (role bypasses all facility checks)
    //  Ops     → Chicago + Detroit
    //  Driver1 → Chicago
    //  Driver2 → Detroit + Milwaukee
    console.log('🔗 Assigning users to facilities...');
    await Promise.all([
        prisma.userFacility.create({ data: { userId: ops!.id,     facilityId: chicago!.id } }),
        prisma.userFacility.create({ data: { userId: ops!.id,     facilityId: detroit!.id } }),
        prisma.userFacility.create({ data: { userId: driver1!.id, facilityId: chicago!.id } }),
        prisma.userFacility.create({ data: { userId: driver2!.id, facilityId: detroit!.id } }),
        prisma.userFacility.create({ data: { userId: driver2!.id, facilityId: milwaukee!.id } }),
    ]);

    // ─── 5. Stations ──────────────────────────────────────────────
    console.log('📟 Creating stations...');
    await Promise.all([
        prisma.station.create({ data: { facilityId: chicago!.id,   token: generateToken(), label: 'Chicago Tablet 1' } }),
        prisma.station.create({ data: { facilityId: chicago!.id,   token: generateToken(), label: 'Chicago Tablet 2' } }),
        prisma.station.create({ data: { facilityId: detroit!.id,   token: generateToken(), label: 'Detroit Tablet 1' } }),
        prisma.station.create({ data: { facilityId: milwaukee!.id, token: generateToken(), label: 'Milwaukee Tablet 1' } }),
    ]);

    // ─── 6. Bin Types ─────────────────────────────────────────────
    console.log('📦 Creating bin types...');
    const binTypes = await Promise.all([
        prisma.binType.create({ data: { organType: 'heart',  dkHours: 4,  urgency: Urgency.CRITICAL, prefix: 'BIN-HEART',  masterQrCode: 'TYPE-HEART' } }),
        prisma.binType.create({ data: { organType: 'liver',  dkHours: 6,  urgency: Urgency.CRITICAL, prefix: 'BIN-LIVER',  masterQrCode: 'TYPE-LIVER' } }),
        prisma.binType.create({ data: { organType: 'kidney', dkHours: 12, urgency: Urgency.MEDIUM,   prefix: 'BIN-KIDNEY', masterQrCode: 'TYPE-KIDNEY' } }),
        prisma.binType.create({ data: { organType: 'skin',   dkHours: 24, urgency: Urgency.STANDARD, prefix: 'BIN-SKIN',   masterQrCode: 'TYPE-SKIN' } }),
        prisma.binType.create({ data: { organType: 'fat',    dkHours: 24, urgency: Urgency.STANDARD, prefix: 'BIN-FAT',    masterQrCode: 'TYPE-FAT' } }),
        prisma.binType.create({ data: { organType: 'bone',   dkHours: 48, urgency: Urgency.LOW,      prefix: 'BIN-BONE',   masterQrCode: 'TYPE-BONE' } }),
    ]);

    // ─── 7. Bins ──────────────────────────────────────────────────
    console.log('🗑️  Creating bins...');
    const binData: Array<[number, number, number]> = [
        // [binTypeIdx, facilityIdx, serialNo]
        // Chicago — 8 bins
        [0, 0, 1], [0, 0, 2], [1, 0, 1], [2, 0, 1], [3, 0, 1], [4, 0, 1], [5, 0, 1], [5, 0, 2],
        // Detroit — 6 bins
        [0, 1, 3], [1, 1, 2], [2, 1, 2], [3, 1, 2], [4, 1, 2], [5, 1, 3],
        // Milwaukee — 6 bins
        [0, 2, 4], [1, 2, 3], [2, 2, 3], [3, 2, 3], [4, 2, 3], [5, 2, 4],
    ];

    await Promise.all(
        binData.map(([t, f, n]) =>
            prisma.bin.create({
                data: {
                    qrCode: `${binTypes[t]!.prefix}-${String(n).padStart(3, '0')}`,
                    binTypeId: binTypes[t]!.id,
                    currentFacilityId: facilities[f]!.id,
                    status: BinStatus.IDLE,
                },
            }),
        ),
    );

    // ─── Done ─────────────────────────────────────────────────────
    console.log('\n✅ Local seed complete!\n');
    console.log('═══════════════════════════════════════════════════════════');
    console.log('  LOCAL DEV — AUTH IS DISABLED (DISABLE_AUTH=true)');
    console.log('═══════════════════════════════════════════════════════════');
    console.log('  The API will auto-inject admin@bintracker.com as the');
    console.log('  acting user for all requests. No login required.');
    console.log('───────────────────────────────────────────────────────────');
    console.log('  USERS CREATED (for reference)');
    console.log('───────────────────────────────────────────────────────────');
    for (const u of dbUsers) {
        console.log(`  ${u.role.padEnd(12)} │ ${u.email}`);
    }
    console.log('───────────────────────────────────────────────────────────');
    console.log('  FACILITY ACCESS');
    console.log('───────────────────────────────────────────────────────────');
    console.log('  ADMIN       → all facilities (no restriction)');
    console.log('  OPS_MANAGER → Chicago + Detroit');
    console.log('  driver1     → Chicago only');
    console.log('  driver2     → Detroit + Milwaukee');
    console.log('═══════════════════════════════════════════════════════════');
    console.log('\n  Servers:');
    console.log('  Frontend → http://localhost:3000');
    console.log('  API      → http://localhost:3001');
    console.log('  Health   → http://localhost:3001/health\n');

    await prisma.$disconnect();
}

main().catch(e => {
    console.error('❌ Local seed failed:', e);
    process.exit(1);
});
