/**
 * seed.local.ts — Local development seed (no Supabase required)
 *
 * Use this when running against a local Postgres instance.
 * Skips Supabase Auth user creation entirely — Prisma generates user IDs via cuid().
 * Requires DISABLE_AUTH=true in .env to bypass JWT verification.
 *
 * Usage: pnpm db:seed:local
 */

import { PrismaClient, FacilityType, UserRole, BinStatus } from '@prisma/client';
import { PrismaPg } from '@prisma/adapter-pg';
import { randomBytes, createHash } from 'crypto';
import { provisionOrganization, DEFAULT_BIN_TYPES } from '../src/org-provision.js';

function generateToken(): string {
    return randomBytes(32).toString('hex');
}

// Tokens are stored hashed at rest (see apps/api/src/lib/token.ts) — the DB
// gets the digest, the console gets the raw value for VITE_TEST_STATION_TOKEN.
function hashToken(raw: string): string {
    return createHash('sha256').update(raw).digest('hex');
}

// ─── Seed Users ─────────────────────────────────────────────────────────────
// IDs are auto-generated by Prisma (cuid). No Supabase required.
// Passwords are listed here for reference only — not stored in the DB since
// there's no auth system in local mode. Log in via DISABLE_AUTH=true.

const SEED_USERS = [
    { email: 'admin@bintracker.com',   name: 'System Admin',  role: UserRole.ADMIN },
    { email: 'ops@bintracker.com',     name: 'Ops Manager',   role: UserRole.OPS_MANAGER },
    { email: 'driver1@bintracker.com', name: 'John Driver',   role: UserRole.DRIVER },
    { email: 'driver2@bintracker.com', name: 'Jane Driver',   role: UserRole.DRIVER },
    { email: 'worker1@bintracker.com', name: 'Bob Worker',    role: UserRole.WORKER },
] as const;

// ─── Main ────────────────────────────────────────────────────────────────────

async function main(): Promise<void> {
    const adapter = new PrismaPg({ connectionString: process.env['DATABASE_URL'] });
    const prisma = new PrismaClient({ adapter, log: [] });

    // ─── Safety guard ────
    // Set SEED_ONLY_IF_EMPTY=true in .env to skip if data already exists.
    // Prevents accidental re-wipes when running seed a second time.
    if (process.env['SEED_ONLY_IF_EMPTY']?.toLowerCase() === 'true') {
        const existing = await prisma.user.findFirst();
        if (existing) {
            console.log('✅ Database already seeded — skipping (SEED_ONLY_IF_EMPTY=true)');
            await prisma.$disconnect();
            return;
        }
    }
    // ─── 1. Clean DB (FK constraint order matters) ────────────────
    console.log('🧹 Cleaning existing data...');
    await prisma.payrollException.deleteMany();
    await prisma.payrollLineItem.deleteMany();
    await prisma.payrollRun.deleteMany();
    await prisma.settings.deleteMany();
    await prisma.attendanceEvent.deleteMany();
    await prisma.workSession.deleteMany();
    await prisma.employee.deleteMany();
    await prisma.shipment.deleteMany();
    await prisma.formTemplate.deleteMany();
    await prisma.animalRegistration.deleteMany();
    await prisma.eventLog.deleteMany();
    await prisma.binCycle.deleteMany();
    await prisma.bin.deleteMany();
    await prisma.station.deleteMany();
    await prisma.binType.deleteMany();
    await prisma.userFacility.deleteMany();
    await prisma.user.deleteMany();
    await prisma.facility.deleteMany();
    // Cascades away Subscription/OrganizationMember/Invitation rows too.
    await prisma.organization.deleteMany();

    // ─── 2. Create users (Prisma generates cuid IDs) ──────────────
    console.log('👤 Creating local users (no Supabase, cuid IDs)...');
    const dbUsers = await Promise.all(
        SEED_USERS.map(u =>
            prisma.user.create({
                data: { email: u.email, name: u.name, role: u.role },
                // No `id` → Prisma auto-generates a cuid()
            }),
        ),
    );
    const [admin, ops, driver1, driver2] = dbUsers;

    // ─── Provision the default org (org + owner membership + bin types +
    // settings + subscription) via the shared provisioning path — same one
    // self-serve signup will use in a later phase. ───
    const { orgId } = await provisionOrganization(prisma, {
        name: 'Default Organization',
        slug: 'default',
        ownerUserId: admin!.id,
    });

    // ─── 3. Facilities ────────────────────────────────────────────
    console.log('🏭 Creating facilities...');
    const facilities = await Promise.all([
        prisma.facility.create({ data: { name: 'Chicago Processing',   type: FacilityType.PROCESSING, address: '123 Industrial Blvd, Chicago, IL 60601',       lat: 41.8781, lng: -87.6298, organizationId: orgId } }),
        prisma.facility.create({ data: { name: 'Detroit Processing',   type: FacilityType.PROCESSING, address: '456 Factory Ave, Detroit, MI 48201',             lat: 42.3314, lng: -83.0458, organizationId: orgId } }),
        prisma.facility.create({ data: { name: 'Milwaukee Processing', type: FacilityType.PROCESSING, address: '789 Plant Rd, Milwaukee, WI 53202',              lat: 43.0389, lng: -87.9065, organizationId: orgId } }),
        prisma.facility.create({ data: { name: 'Midwest Rendering',    type: FacilityType.RENDERING,  address: '321 Render Lane, Indianapolis, IN 46201',        lat: 39.7684, lng: -86.1581, organizationId: orgId } }),
        prisma.facility.create({ data: { name: 'Great Lakes Rendering',type: FacilityType.RENDERING,  address: '654 Process Way, Columbus, OH 43215',            lat: 39.9612, lng: -82.9988, organizationId: orgId } }),
    ]);
    const [chicago, detroit, milwaukee] = facilities;

    // ─── 4. Assign users to facilities ───────────────────────────
    //  ADMIN   → no assignment (role bypasses all facility checks)
    //  Ops     → Chicago + Detroit
    //  Driver1 → Chicago
    //  Driver2 → Detroit + Milwaukee
    console.log('🔗 Assigning users to facilities...');
    await Promise.all([
        prisma.userFacility.create({ data: { userId: ops!.id,     facilityId: chicago!.id } }),
        prisma.userFacility.create({ data: { userId: ops!.id,     facilityId: detroit!.id } }),
        prisma.userFacility.create({ data: { userId: driver1!.id, facilityId: chicago!.id } }),
        prisma.userFacility.create({ data: { userId: driver2!.id, facilityId: detroit!.id } }),
        prisma.userFacility.create({ data: { userId: driver2!.id, facilityId: milwaukee!.id } }),
    ]);

    // ─── 5. Stations ──────────────────────────────────────────────
    console.log('📟 Creating stations...');
    const stationSpecs = [
        { facilityId: chicago!.id,   label: 'Chicago Tablet 1' },
        { facilityId: chicago!.id,   label: 'Chicago Tablet 2' },
        { facilityId: detroit!.id,   label: 'Detroit Tablet 1' },
        { facilityId: milwaukee!.id, label: 'Milwaukee Tablet 1' },
    ].map((spec) => ({ ...spec, rawToken: generateToken() }));
    await Promise.all(
        stationSpecs.map((s) =>
            prisma.station.create({ data: { facilityId: s.facilityId, token: hashToken(s.rawToken), label: s.label } }),
        ),
    );
    console.log('   Raw station tokens (stored hashed — copy one into VITE_TEST_STATION_TOKEN for kiosk dev):');
    for (const s of stationSpecs) console.log(`   ${s.label}: ${s.rawToken}`);

    // ─── 6. Bin Types ─────────────────────────────────────────────
    // Already created by provisionOrganization() above — fetch them back in
    // the same order as DEFAULT_BIN_TYPES so binData below can still index
    // into them positionally (0=heart, 1=liver, 2=kidney, 3=skin, 4=fat, 5=bone).
    const seededBinTypes = await prisma.binType.findMany({ where: { organizationId: orgId } });
    const binTypeByOrganType = new Map(seededBinTypes.map((bt) => [bt.organType, bt]));
    const binTypes = DEFAULT_BIN_TYPES.map((bt) => binTypeByOrganType.get(bt.organType)!);

    // ─── 7. Bins ──────────────────────────────────────────────────
    console.log('🗑️  Creating bins...');
    const binData: Array<[number, number, number]> = [
        // [binTypeIdx, facilityIdx, serialNo]
        // Chicago — 8 bins
        [0, 0, 1], [0, 0, 2], [1, 0, 1], [2, 0, 1], [3, 0, 1], [4, 0, 1], [5, 0, 1], [5, 0, 2],
        // Detroit — 6 bins
        [0, 1, 3], [1, 1, 2], [2, 1, 2], [3, 1, 2], [4, 1, 2], [5, 1, 3],
        // Milwaukee — 6 bins
        [0, 2, 4], [1, 2, 3], [2, 2, 3], [3, 2, 3], [4, 2, 3], [5, 2, 4],
    ];

    await Promise.all(
        binData.map(([t, f, n]) =>
            prisma.bin.create({
                data: {
                    qrCode: `${binTypes[t]!.prefix}-${String(n).padStart(3, '0')}`,
                    binTypeId: binTypes[t]!.id,
                    currentFacilityId: facilities[f]!.id,
                    status: BinStatus.IDLE,
                    organizationId: orgId,
                },
            }),
        ),
    );

    // ─── Done ─────────────────────────────────────────────────────
    console.log('\n✅ Local seed complete!\n');
    console.log('═══════════════════════════════════════════════════════════');
    console.log('  LOCAL DEV — AUTH IS DISABLED (DISABLE_AUTH=true)');
    console.log('═══════════════════════════════════════════════════════════');
    console.log('  The API will auto-inject admin@bintracker.com as the');
    console.log('  acting user for all requests. No login required.');
    console.log('───────────────────────────────────────────────────────────');
    console.log('  USERS CREATED (for reference)');
    console.log('───────────────────────────────────────────────────────────');
    for (const u of dbUsers) {
        console.log(`  ${u.role.padEnd(12)} │ ${u.email}`);
    }
    console.log('───────────────────────────────────────────────────────────');
    console.log('  FACILITY ACCESS');
    console.log('───────────────────────────────────────────────────────────');
    console.log('  ADMIN       → all facilities (no restriction)');
    console.log('  OPS_MANAGER → Chicago + Detroit');
    console.log('  driver1     → Chicago only');
    console.log('  driver2     → Detroit + Milwaukee');
    console.log('═══════════════════════════════════════════════════════════');
    console.log('\n  Servers:');
    console.log('  Frontend → http://localhost:3000');
    console.log('  API      → http://localhost:3001');
    console.log('  Health   → http://localhost:3001/health\n');

    await prisma.$disconnect();
}

main().catch(e => {
    console.error('❌ Local seed failed:', e);
    process.exit(1);
});
